### ISSUE TITLE
Bug with Elixtagram.user_feed

### ISSUE THREAD

**Issue by abitdodgy** [Zensavona/elixtagram#17]
I was playing around with the lib in the console and tried to use `Elixtagram.user_feed(%{count: 2}, :global)`. I got the following error:

```
[iex(13)> Elixtagram.user_feed(%{count: 2}, :global)
** (Poison.SyntaxError) Unexpected token at position 0: <
        (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
        (poison) lib/poison.ex:83: Poison.decode!/2
    (elixtagram) lib/elixtagram/api/base.ex:43: Elixtagram.API.Base.handle_response/1
    (elixtagram) lib/elixtagram/api/users.ex:58: Elixtagram.API.Users.feed/2
```

Elixir 1.3.4

**Comment by Zensavona** [comment]
Hi @abitdodgy, I just tried this but can't reproduce it, could you describe the exact steps you took leading up to this error?

Sorry for the late reply.

Thanks!

**Comment by wulymammoth** [comment]
Elixir v1.4.2
Phoenix v1.3.0-rc

I'm running into an error related to user feed as well:
```elixir
iex> Elixtagram.user_feed(%{count: 2}, :global)
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[ok: "3385335.9079f55.f49fd78387ba4364b4e4161c87483ff9"]

        (elixir) lib/list.ex:709: List.to_string/1
    (elixtagram) lib/elixtagram/api/base.ex:86: Elixtagram.API.Base.params_join/2
    (elixtagram) lib/elixtagram/api/base.ex:70: Elixtagram.API.Base.build_url/2
    (elixtagram) lib/elixtagram/api/base.ex:15: Elixtagram.API.Base.get/3
    (elixtagram) lib/elixtagram/api/users.ex:58: Elixtagram.API.Users.feed/2
```

**Comment by wulymammoth** [comment]
My previous comment is a non-issue (related to README example), but I'm going to open a PR to fix the issue @abitdodgy and I are experiencing as Instagram has updated its endpoint for user feeds resulting in a 404 page (text/html) response.

PR [here](https://github.com/Zensavona/elixtagram/pull/20)
