### ISSUE TITLE
Cannot run in iex session

### ISSUE THREAD

**Issue by allenwyma** [Zensavona/elixtagram#6]
Maybe I'm missing something, but not sure what. I used mix to create a new app:

`mix new whatever`

I then use `iex -S mix` to get to an interactive session, but I can't seem to login with the authorize_url! function:

```
iex(1)> Elixtagram.authorize_url!
** (exit) exited in: GenServer.call(Elixtagram.Config, {:get, #Function<0.72457492/1 in Elixtagram.Config.get/0>}, 5000)
    ** (EXIT) no process
        (elixir) lib/gen_server.ex:564: GenServer.call/3
    (elixtagram) lib/elixtagram/oauth_strategy.ex:11: Elixtagram.OAuthStrategy.new/0
    (elixtagram) lib/elixtagram/oauth_strategy.ex:43: Elixtagram.OAuthStrategy.authorize_url!/0
iex(1)> Elixtagram.Config.get
** (exit) exited in: GenServer.call(Elixtagram.Config, {:get, #Function<0.72457492/1 in Elixtagram.Config.get/0>}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:564: GenServer.call/3
iex(1)> Dotenv.load
%Dotenv.Env{paths: ["/Users/user/Documents/workspace/elixir/whatever/.env"],
 values: #HashDict<[{"INSTAGRAM_CLIENT_ID", "xxx"},
  {"INSTAGRAM_CLIENT_SECRET", "xxx"},
  {"INSTAGRAM_REDIRECT_URI", "http://example.com/index.php"}]>}
```

mix file:

``` elixir
defmodule Whatever.Mixfile do
  use Mix.Project

  def project do
    [app: :whatever,
     version: "0.0.1",
     elixir: "~> 1.2",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: app_list(Mix.env)]
  end

  defp app_list(:dev), do: [:dotenv | app_list]
  defp app_list(_), do: app_list
  defp app_list, do: [:logger, :elixtagram]

  defp deps do
    [
        {:dotenv, github: "avdi/dotenv_elixir"},
        {:elixtagram, "~> 0.2.6"}
    ]
  end
end
```

**Comment by Zensavona** [comment]
Run `Elixtagram.configure` first :)

**Comment by allenwyma** [comment]
👍  wasn't clear from the README, but got it now.

**Comment by radzserg** [comment]
Yeah I also got this issue. Please update README. Thanks

**Comment by Zensavona** [comment]
@HangingClowns & @radzserg done :)
